### ISSUE TITLE
Undefined functions in cocktail_party.m

### ISSUE THREAD

**Issue by abhikandoi2000** [priyathamkat/cocktail-party-problem#1]
The functions `G` and `DG` are used in the file `cocktail_party.m` but are undefined.

Can you please tell what these functions are for?

**Comment by kmspriyatham** [comment]
Sorry about that. G is the function tanh(x) and DG is its derivative (1-tanh^2(x))

**Comment by abhikandoi2000** [comment]
Thanks

**Comment by abhikandoi2000** [comment]
You might want to close this issue after you push the updated code. Leaving it up to you.
